services:
    api:
        build: .
        container_name: f1api
        env_file: .env.example
        environment:
            DATABASE_URL: postgresql+psycopg://f1:f1password@postgres:5432/f1db
        ports:
            - "8000:8000"
        depends_on:
            - postgres
        volumes:
            - ./:/app:delegated
        command: >
            uv run uvicorn f1api.main:app
            --host 0.0.0.0 --port 8000 --reload

    postgres:
        image: postgres:16-alpine
        container_name: f1db
        environment:
            POSTGRES_USER: f1
            POSTGRES_PASSWORD: f1password
            POSTGRES_DB: f1db
        ports:
            - "5432:5432"
        volumes:
            - f1pgdata:/var/lib/postgresql/data

volumes:
    f1pgdata:
