"""fix season relationships

Revision ID: 877a240c7ef0
Revises: 6c9ec75873f3
Create Date: 2025-09-29 14:52:51.641481

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "877a240c7ef0"
down_revision: Union[str, None] = "6c9ec75873f3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
